### ISSUE TITLE
Active development

### ISSUE THREAD

**Issue by twallbaum** [Kitsune-tools/Ana-App#2]
Hi,
we would like to use Ana for research purposes and were wondering if this project is under active development? If that is the case, is there a way to get some more documentation for using Ana-Studio and for creating more complex conversations?
Thanks for your help 👍

**Comment by NizamLZ** [comment]
Hello,
Glad to know that you want to use Ana for your research. Yes, this project is under active development. 
We will provide more documentation for the same, soon.
In the meanwhile, we can arrange a call with you and explain how complex flows are made in Ana studio and to what extent its already being used. Please mail us your contact details at hello@ana.chat.
